### PR TITLE
Initialize router without macro

### PR DESCRIPTION
**Pull request by dbrgn**
I don't think the macro creates any added value, besides one less mut variable.

This would also solve #19.

### CODE REVIEW

**Comment by rnestler** [comment]
Why would it solve #19?

**Comment by dbrgn** [comment]
We already upgraded the `router` package. And then we don't have to add trailing commas because we're not using the macro ;)

**Comment by rnestler** [comment]
So "solve" is just the wrong word it's just not applicable anymore :grin:

But anyway in #15 we argued that the macro may one day validate the routes and thus provide more safety, but I don't think that this will happen anytime soon.

**Comment by dbrgn** [comment]
Yeah, I think right now it's even slower than the regular code.

**Pull request merged**
