### PR TITLE
Add support for clippy

### PR DESCRIPTION
**Pull request by rnestler**
Also fixes the issues noted in #47

### CODE REVIEW

**Comment by dbrgn** [comment]
Haha, you forgot to add the "unstable" feature :)

**Comment by rnestler** [comment]
@dbrgn Nah I just named it wrongly :cry:

**Comment by dbrgn** [comment]
Cool! Let's merge this as soon as the tests pass, and fix the warnings in a separate PR. I can do that.

**Comment by rnestler** [comment]
> ...fix the warnings in a separate PR. I can do that.

Or maybe use this as an easy issue? Maybe someone at @coredump-ch wants learn some Rust :smiley:

**Comment by dbrgn** [comment]
:+1: good idea :)

**Comment by dbrgn** [comment]
Can you create the issues?

**Pull request merged**
