### PR TITLE
Get rid of DataStore abstraction

### PR DESCRIPTION
**Pull request by dbrgn**
I think we should remove the DataStore abstraction and use Redis directly, for the following reasons:

- Right now we don't need it, except for testing. And even when testing on Travis, we can add a Redis server with just 2 lines in the config file.
- The DataStore is an unnecessary abstraction that prevents us from fully taking advantage of Redis.
- The DataStore does away with datatypes and stores everything as strings. With Redis we could use real numeric types.
- Redis supports lists and atomic operations like "get and delete". This can be used to implement the session tokens.
- Redis supports key expiration. So we can expire session tokens after a minute without having to write the logic ourselves.
- Other datastores? YAGNI!

Do you agree, @coredump-ch/spaceapi?

### CODE REVIEW

**Comment by dbrgn** [comment]
Wow, this got pretty big and messy: 125 lines added, 244 lines removed.

The second commit does various things:

    - Remove the datastore module and all datastore implementations
    - Replace the datastore instance in the `SpaceapiServer` with a
      Redis `ConnectionInfo` object.
    - This object is passed around to the handlers instead of the datastore
      Arc Mutex.
    - Previously the datastore access was inconsistent: Sometimes the
      sensor specs fetched their own values, but sometimes we updated the
      values in the datastore directly, without going through the sensor
      spec. In the current codebase, the sensor specs are responsable for
      accessing Redis to fetch or update sensor values.

(No, it was not easily possible to split these things up into multiple commits!)

Right now everything compiles without a warning (which is a very good sign), but I'll first have to test this. Unfortunately we don't have any tests anymore, so I'll probably write some instead of simply recompiling the coredump status with this version of the spaceapi-server.

I'll also improve the documentation in a separate step (probably even in a separate PR).

@rnestler if you already want to take a quick look at it, you may. I believe this change made the codebase as a whole easier to read.

**Comment by dbrgn** [comment]
Rebased against #8. @rnestler, do you have time to take a look?

**Comment by rnestler** [comment]
Ohm, since I merged #8 you should maybe rebase it again...

**Comment by dbrgn** [comment]
Yep, done :)

**Comment by dbrgn** [comment]
Can we merge this?

**Comment by rnestler** [comment]
:+1:

**Comment by dbrgn** [comment]
Wohoo!

**Pull request merged**
