### PR TITLE
Reduce clone depth for CI

### PR DESCRIPTION
**Pull request by dns2utf8**
This should build the example code as well as I am currently no sure this happens.

### CODE REVIEW

**Comment by dbrgn** [comment]
Aren't examples built by default?

**Comment by dns2utf8** [comment]
You are right, they are. Changed the title

**Comment by dbrgn** [comment]
We don't need to link travis tests to specific commit hashes, right? These will change with a shallow clone: https://stackoverflow.com/questions/31278233/disadvantages-of-shallow-cloning-on-travis-and-other-ci-services

**Comment by dns2utf8** [comment]
Aha, so leaving it as is?

**Comment by dbrgn** [comment]
No, not necessarily :) If it doesn't hurt and speeds up the build we can do a shallow clone. I was just asking whether we rely on the commit hashes somewhere. In that case, this would break the commit hash referencing. Might happen when using tools like coveralls.

@rnestler opinions?

**Pull request closed without merging**
