### PR TITLE
Use travis-cargo

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by dbrgn** [comment]
Woah, coverage even works: https://coveralls.io/builds/5398182 Last time I tried travis-cargo it didn't work :)

**Comment by rnestler** [comment]
I had to setup an account and link it to github.

**Comment by rnestler** [comment]
What's with the documentation? I don't think it worked did it?

**Comment by dbrgn** [comment]
> What's with the documentation? I don't think it worked did it?

Doesn't look like it...

**Comment by dbrgn** [comment]
I think we need to set up encrypted keys somehow.

**Pull request merged**
