### PR TITLE
Simplify examples

### PR DESCRIPTION
**Pull request by rnestler**
* Use the ApiBuilder
* Use the Default trait

### CODE REVIEW

**Comment by dbrgn** [comment]
Li lukin pona tawa mi. But we should probably wait for the next spaceapi-rs release before merging this.

**Comment by rnestler** [comment]
> **ni li** lukin pona tawa mi. But we should probably wait for the next spaceapi-rs release before merging this.

Yes of course we should wait, direct git dependencies are evil.

**Comment by dbrgn** [comment]
Ass 😄

**Comment by dbrgn** [comment]
Can we merge this now, @rnestler?

**Comment by dbrgn** [comment]
Blocked by https://github.com/coredump-ch/spaceapi-rs/pull/47.

We should either release a 0.4.2 with a fix or merge extension fields as well and release 0.5.0.

**Comment by rnestler** [comment]
> We should either release a 0.4.2 with a fix or merge extension fields as well and release 0.5.0.

I would prefer a 0.4.2 release first, so we can merge these without needing to fix all the breaking changes.

**Comment by dbrgn** [comment]
Released: https://crates.io/crates/spaceapi

**Pull request merged**
