### PR TITLE
Upgrade iron / hyper dependencies

### PR DESCRIPTION
**Pull request by dbrgn**
This is a potentially breaking change, as we re-export `iron::error::HttpResult` and `hyper::server::Listening`.

### CODE REVIEW

**Comment by dns2utf8** [comment]
can you rebase it?

**Comment by dns2utf8** [comment]
Yes this is a breaking change. Prepared the status

**Comment by dbrgn** [comment]
Rebased.

**Comment by dbrgn** [comment]
As there were no objections, I'll merge this.

**Pull request merged**
